import '@/styles/global.css'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { VideoDataProvider } from './_context/videoDataContext'
import { ThemeProvider } from '../components/theme/theme-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const font = Inter({ subsets: ['latin'] })
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            'min-h-screen bg-background text-foreground antialiased max-w-full overflow-x-hidden',
            font.className
          )}
        >
          <VideoDataProvider>
            <Toaster />
            {/* <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            > */}
            {children}
            {/* </ThemeProvider> */}
          </VideoDataProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
